#!/usr/bin/env -S mise tool-stub
bin = "goreleaser"

[platforms.darwin-arm64]
url = "https://github.com/goreleaser/goreleaser/releases/download/v2.14.0/goreleaser_Darwin_all.tar.gz"
checksum = "sha256:c0aadc388800aeb8cbe6bbef6d7832c087adb09bdcea193795dfa14126a6377a"

[platforms.darwin-amd64]
url = "https://github.com/goreleaser/goreleaser/releases/download/v2.14.0/goreleaser_Darwin_all.tar.gz"
checksum = "sha256:c0aadc388800aeb8cbe6bbef6d7832c087adb09bdcea193795dfa14126a6377a"

[platforms.linux-amd64]
url = "https://github.com/goreleaser/goreleaser/releases/download/v2.14.0/goreleaser_Linux_x86_64.tar.gz"
checksum = "sha256:95e3a3a2adeacd1b8dd704743c71eec8343dde472d3efe71101a62570c47cbbd"

[platforms.linux-arm64]
url = "https://github.com/goreleaser/goreleaser/releases/download/v2.14.0/goreleaser_Linux_arm64.tar.gz"
checksum = "sha256:1c0347661912e006259d4048549c9b4af51770b6b386759ee2df972ce87426fc"

[platforms.windows-amd64]
url = "https://github.com/goreleaser/goreleaser/releases/download/v2.14.0/goreleaser_Windows_x86_64.zip"
checksum = "sha256:2cf253fa3a2b89fd2265032a1cd50cfbd7a6ae09223b909cbc21314454e14942"
bin = "goreleaser.exe"
